-- MySQL Script generated by MySQL Workbench
-- sáb 21 set 2019 12:25:40 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(55) NOT NULL,
  `matricula` VARCHAR(25) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `status` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

-- -----------------------------------------------------
-- Usuário cadastrado: Matricula: 20141cxcc0012 senha: 123
-- -----------------------------------------------------
INSERT INTO `usuarios` VALUES (1,'Francisco Sousa','20141cxcc0012','202cb962ac59075b964b07152d234b70','2019-09-22 08:43:07',1);

-- -----------------------------------------------------
-- Table `clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(55) NOT NULL,
  `cpf` VARCHAR(20) NOT NULL,
  `rg` VARCHAR(20) NOT NULL,
  `endereco` VARCHAR(55) NOT NULL,
  `numero` VARCHAR(15) NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `renda` DECIMAL(10,2) NOT NULL,
  `usuarios_id` INT NOT NULL,
  `created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `status` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `produtos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  `preco_vista` DECIMAL(10,2) NOT NULL,
  `preco_prazo` DECIMAL(10,2) NOT NULL,
  `codigo_barras` VARCHAR(45) NOT NULL,
  `usuarios_id` INT NOT NULL,
  `created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `status` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vendas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `produtos_id` INT NULL,
  `clientes_id` INT NULL,
  `quantidade` INT NOT NULL,
  `forma_pagamento` VARCHAR(15) NOT NULL,
  `data` TIMESTAMP NULL,
  `valor_total` DECIMAL(10,2) NOT NULL,
  `usuarios_id` INT NULL,
  `created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `status` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_vendas_produtos_idx` (`produtos_id` ASC),
  INDEX `fk_vendas_clientes_idx` (`clientes_id` ASC),
  CONSTRAINT `fk_vendas_produtos`
    FOREIGN KEY (`produtos_id`)
    REFERENCES `produtos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_vendas_clientes`
    FOREIGN KEY (`clientes_id`)
    REFERENCES `clientes` (`id`)
    ON DELETE CASCADE 
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;




SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
